project:
  type: website
  output-dir: "_site"

## NB: Folder and file names are case-sensitive!

website:
  title: "Kandidatundersøkelsene: Halvtårsundersøkelsen"
  navbar:
    logo: "https://www.nifu.no/wp-content/uploads/logo_hvit.png"
    left:
      - sidebar:Rapporter
  sidebar:
#    - id: Rapporter
      title: "Rapporter"
      contents: "Rapporter"
      
project_no: "21395-1"
funder: "Direktoratet for høyere utdanning og kompetanse (HK-dir)"
funder_address: "Fortunen 1, 5013 Bergen"

execute:
  freeze: auto
  cache: false

metadata-files:
  - _global.yaml # Must be in same folder/subfolder
