params$reportnumber <- "2023:X"
params$prefacetext <-  ""
params$prefaceAuthorA <- "Vibeke Opheim"
params$prefaceAuthorAposition <- "Direktør"
params$prefaceAuthorB <- "Jannecke Wiers-Jenssen"
params$prefaceAuthorBposition <- "Forskningsleder"
params$projectnumber <- "21395-1"
params$isbn <- "978-82-327-0000-0"
params$projectowner <- "Kunnskapsdepartementet"
params$projectowneraddress <- ""